### ISSUE TITLE
posodobitev povezave

### ISSUE THREAD

**Issue by VidStarc** [jaanos/APPR-2014-15-zagovori#1]
VidStarc/APPR-2014-15@bf235a5f1837c95233f577f153bf31b40ba243fb

**Comment by jaanos** [comment]
Te šifre commita nimaš v svojem repozitoriju (če klikneš nanjo, dobiš napako). V svojem repozitoriju imaš en sam nov commit, tako da sem tega upošteval:

VidStarc/APPR-2014-15@4dcf9f2ec0c0e0d6b9851595838b77d5c3f52d6d

**Comment by VidStarc** [comment]
Posodobil sem poročilo in sicer slike so sedaj večje, torej bi mogel biti
ta commit zadnji in končen. Nevem kje se zalomi.

Dne 15. januar 2015 19.59 je Janoš Vidali <notifications@github.com>
napisal/-a:

**Comment by jaanos** [comment]
Očitno se je nekaj narobe skopiralo (včasih se to zgodi, ne vem, zakaj) - zato se splača preveriti, če nastala povezava res kaže na pravi commit.

Kakorkoli, je urejeno.
