### ISSUE TITLE
Zaključek projekta

### ISSUE THREAD

**Issue by nolimal** [jaanos/APPR-2014-15-zagovori#12]
Spoštovani, 

zaključil sem projekt. Naprošam Vas, da mi sporočite če je vse O.K., da bi kar se da hitro prišel na ustni zagovor.

Lepo Vas pozdravljam, 
Nolimal Matevž.

**Comment by jaanos** [comment]
Je večinoma v redu, tako bom dodal povezavo na trenutno stanje repozitorija. Dobiš še en pull request z nekaj predlogi in komentarji.

S profesorjem se lahko domeniš za datum zagovora, če pa boš še kaj spreminjal, pa javi tukaj (lahko ponovno odpreš ta issue, ali pa odpreš novega).
