### ISSUE TITLE
Koncna verzija

### ISSUE THREAD

**Issue by LacenS** [jaanos/APPR-2014-15-zagovori#31]
Mislim, da sem koncala, sporocite ce je kaj narobe.
V porocilu imam vkljucene tudi animacije, ki pri meni ne delujejo (mac), ampak mislim da bi drugje morale delovat, pa naredila sem tudi html verzije, ki jih pa nisem vkljucila v porocilo, sem pa opisala kako se pozenejo.
hvala
lp

**Comment by jaanos** [comment]
Programa žal ne zažene - glej LacenS/APPR-2014-15#10.

Animacije ti bodo delovale, če poročilo odpreš v Adobe Readerju.
