### ISSUE TITLE
Končna verzija.

### ISSUE THREAD

**Issue by nejapletikos** [jaanos/APPR-2014-15-zagovori#32]
S projektom sem načeloma zaključila.
Moj repozitorij: Neja-Pletikos @ abb1a51

Lep pozdrav.

**Comment by jaanos** [comment]
Programa ne zažene - ustavi se pri poskusu uvoza iz datoteke `podatki/polokaciji.csv`, ki pa je na GitHubu nimaš naložene,

**Comment by nejapletikos** [comment]
Sedaj sem naložila še datoteke na GitHub. Meni program ne javi nobene napake ko ga zaženem na svojem računalniku, tako da niti ne vem kaj popraviti.

**Comment by jaanos** [comment]
Sedaj je vse v redu, tako da sem dodal. Svetoval bi ti sicer še, da v poročilu natančneje opišeš uvožene razpredelnice (za vsako poveš, katere stolpce ima, ter kakšne podatke ti vsebujejo).

Če boš še kaj spreminjala, odpri nov issue na repozitoriju za zagovore (ali pa ponovno odpri tega), da posodobim povezavo. Če se še nisi, se s profesorjem domeni za termin zagovora.
