### ISSUE TITLE
zaključek projekta

### ISSUE THREAD

**Issue by Ahcinn13** [jaanos/APPR-2014-15-zagovori#34]
zaključek projekta

**Comment by jaanos** [comment]
Program se ustavi, ko skušaš PDF-je risati v mape `slike/graf`, `slike/zemljevidi` in `slike/analiza`, ki pa so prazne (oziroma imaš v njih samo PDF-je) in jih zato ni v repozitoriju, posledično pa program zaradi tega ne deluje. Svetujem, da v vsaki od njih narediš eno datoteko, npr. `README.md`, kjer opišeš, kaj naj bi bilo v tej mapi (lahko pa to datoteko pustiš tudi prazno), in seveda te datoteke vključiš v commit.

**Comment by jaanos** [comment]
Vidim, da si popravila, tako da sem dodal. Če bi pa še kaj spreminjala, odpri nov issue oziroma ponovno odpri tega. Če se še nisi, se s profesorjem domeni za termin zagovora.

**Comment by jaanos** [comment]
Sprememba poročila Ahcinn13/APPR-2014-15@adc120df5273e1f4e93c8218a8985e193ebf6b7d tukaj še ni zajeta, tako da javi, če si končala, oziroma ko boš, da posodobim povezavo.

**Comment by Ahcinn13** [comment]
končano

**Comment by Ahcinn13** [comment]
V zadnji spremembi so zgolj nekateri popravki poročila.

**Comment by jaanos** [comment]
V redu, sem posodobil.
