### ISSUE TITLE
Končan projekt

### ISSUE THREAD

**Issue by jlenarcic** [jaanos/APPR-2014-15-zagovori#39]
S projektom sem zaključil že 1.3. (torej v roku), vendar sem povsem pozabil odpreti tale issue, zato ga odpiram zdaj. Prosim, če greste skozi projekt in mi sporočite, če bi morda moral še kaj popraviti.

Lep pozdrav.

**Comment by jaanos** [comment]
Poročila ti ne prevede - problem je, ker postavljaš prelome vrstic (`\\`) na začetke odstavkov, kar LaTeXu ni všeč. Prelome vrstic uporabljaj samo takrat, ko hočeš v novo vrstico brez novega odstavka (torej prazne vrstice); drugod raje enostavno pusti prazno vrstico pred novim odstavkom. Če želiš pustiti nekaj prostora med odstavki, uporabi npr. `\smallskip`, `\medskip` ali `\bigskip`. Poleg tega imaš pti tretji referenci en odvečen zavit oklepaj.

V poročilo dodaj še enačbe krivulj za modele, ki jih prikazuješ.

**Comment by jlenarcic** [comment]
Popravil napake. V poročilo sem dodal enačbe za krivulje pri modelih.

**Comment by jaanos** [comment]
Sem dodal povezavo. Če se še nisi, se s profesorjem domeni za termin zagovora.

**Comment by jlenarcic** [comment]
Danes sem bil pri profesorju na zagovoru in že dobil oceno, le nekatere malenkosti sem še moral izboljšati. Sedaj pa sem popravil še zadnje stvari v poročilu , tako da imam sedaj zadnjo verzijo poročila.

Lep pozdrav

**Comment by jaanos** [comment]
Sem posodobil povezavo.
