### ISSUE TITLE
Pregled projekta in zagovor

### ISSUE THREAD

**Issue by filiplenarcic** [jaanos/APPR-2014-15-zagovori#40]
Prosil bi vas, če bi lahko pregledali moj projekt pred zagovorom.

Lep pozdrav,

Filip Lenarčič

**Comment by jaanos** [comment]
Poročila ti ne prevede - vrstici 147 in 169 imaš odvečne zavite oklepaje.

Svetujem ti še, da v stolpčnih diagramih urediš ekipe oziroma igralce glede na prikazan podatek (da bo takoj vidno, kdo je boljši v tem pogledu). Pri analizi si zgradil tako linearni kot tudi kvadratni model, a sta praktično enaka. Zato svetujem, da kvadratnega izpustiš (lahko v poročilu omeniš, da se ni bistveno razlikoval od linearnega). Za linearni model v poročilu napiši tudi enačbo dobljene premice.

Ko popraviš, javi tukaj, da dodam povezavo. Če se še nisi, se s profesorjem domeni za termin zagovora.

**Comment by filiplenarcic** [comment]
Urejeno in popravljeno.

**Comment by jaanos** [comment]
Opažam, da so oznake pri grafu zadetkov igralcev napačne - bo treba prej preurediti vrstice, šele nato pobrati ven priimke. Pri grafu izkoriščenih powerplayev lahko nekoliko še zmanjšaš oznake, da jih ne bo odrezalo.

**Comment by filiplenarcic** [comment]
Popravljene tudi te zadeve.

**Comment by filiplenarcic** [comment]
Po dogovoru s profesorjem sem dodal še oznake opisom spremenljivk. Tako je to končna verzija projekta.

LP

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo.
