### ISSUE TITLE
končala animaciji

### ISSUE THREAD

**Issue by LeaTehovnik** [jaanos/APPR-2014-15-zagovori#43]
Po dogovoru s profesorjem sem dodala še animaciji in sedaj končala s projektom. 
Čudno mi je edino to, da mi na faksu animacije (v Adobe) ne predvaja, doma pa, no ampak saj verjetno je prav.

**Comment by jaanos** [comment]
Animaciji ne delujeta, ker `cairo_pdf` privzeto nariše v PDF samo zadnji graf. Da bo delovalo, dodaj h klicema funkcije `mypdf` za animaciji še parameter `onefile = TRUE` (doma ne bo razlike, ker je to privzeta vrednost za `pdf`).

Še eno malenkost sem opazil: pri prvem tortnem grafu imaš neprevedeno ime `West Germany`.

Ko to urediš, javi kar tukaj, da posodobim povezavo.

**Comment by LeaTehovnik** [comment]
Odpravila vse napake in zaključila.
